### PR TITLE
Change install to handle empty Container.Installer

### PR DESCRIPTION
**Pull request by mimi89999**
When options.Container.Installer is empty and container contains only
one file use it as the installer.

This solves the issue in https://github.com/just-install/registry/pull/229. `installer` file is different in every release, but since it's the only file in the container we actually don't need to know the name.

### CODE REVIEW

**Comment by mimi89999** [comment]
@lvillani @pgaskin Please review.

**Review by pgaskin — APPROVED** [review]
Looks good, but I haven't tested it.

**Comment by lvillani** [comment]
This looks good, but I'm very busy these days and cannot test this at the moment. I might be able to find some time this week-end.

**Comment by mimi89999** [comment]
@lvillani OK. Thanks a lot. I also think that we should prepare for a new release of j-i.

**Comment by lvillani** [comment]
LGTM. Allowing `container.installer` to be empty is a backwards-incompatible change that will probably require a registry version bump.

Maybe we can change the current registry (v4) to support the new format, we'll break users of old versions for one single package (rationale is: it would be more effort to bump the registry and change our processes than asking the - I believe extremely small - subset of users to upgrade). We'll need to think about this.

**Comment by pgaskin** [comment]
I personally believe changing the currently registry format and avoiding using this feature unless absolutely necessary is the best option:

- This is only necessary for a few packages.
- Users of those packages wouldn't be able to install them without the change in the first place.
- The change will just break for older j-i versions; it won't be parsed incorrectly and cause issues.
- I'd consider this to be more of a j-i change than a registry change.

**Comment by mimi89999** [comment]
https://github.com/just-install/just-install/pull/320 will also break Mozilla apps on old j-i versions. I think that it's finally time to make a new release. Users will just download the new version from the website.

**Pull request merged**
