### PR TITLE
Add appx package support to the installer

### PR DESCRIPTION
**Pull request by mimi89999**

### CODE REVIEW

**Comment by mimi89999** [comment]
@lvillani Could you make a new release so I can start adding apps to the repo?

**Comment by geek1011** [comment]
@mimi89999, this also needs to be added to the JSON schema in the registry.

**Comment by mimi89999** [comment]
Should I add it even if the latest release doesn't support it? `jetbrains-nsis` was added to j-i, but is not in the release yet and it is not in the schema.

**Comment by geek1011** [comment]
Yes. It's only used for validation, so we might as well do it earlier. Also, we don't necessarily need to merge it until j-i is released.

**Comment by lvillani** [comment]
We'll have to backport this change if we want an immediate release. There are too many not fully baked commits since `v3.4.7` that I don't feel safe to release the current `master` as-is.

**Comment by mimi89999** [comment]
@lvillani Could you please backport it and the `jetbrains-nsis` installer and make a new release?

**Comment by lvillani** [comment]
I'm a bit swamped by other commitments. I'll see what I can do (should be an easy thing to backport anyway).

**Pull request merged**
