### PR TITLE
Added just-install customizer (#221)

### PR DESCRIPTION
**Pull request by geek1011**
I have added the customizer to the site. 

The only disadvantage is that just-install.exe will have to be updated manually with each release. The page accesses just-install.exe with XHR, and bintray does not support CORS, so this is the only way to do it easily.

### CODE REVIEW

**Comment by geek1011** [comment]
There is a demo here: https://www.bitballoon.com/sites/just-install-customizer-demo

**Comment by geek1011** [comment]
@lvillani Can you have a look at this?

**Comment by lvillani** [comment]
@geek1011 looks like the demo page is down. I looked at it from my mobile a while ago and it looked nice, tho.

**Comment by lvillani** [comment]
I'm trying this locally and it seems to work just fine. My only concern is file name lengths limitations, especially when users add lots of packages to the installer, in which case the file name becomes really long.

**Comment by lvillani** [comment]
Btw, I'm also changing the deployment process to publish to an S3 bucket instead of Bintray, I should be able to configure CORS over there.

**Comment by lvillani** [comment]
It's live! http://just-install.it/customizer.html

**Pull request closed without merging**
