### PR TITLE
Add language placeholder

### PR DESCRIPTION
**Pull request by mimi89999**
Currently only tested against Firefox and Thunderbird as I don't know many other apps with this issue.

### CODE REVIEW

**Comment by mimi89999** [comment]
@lvillani Please review.

**Comment by lvillani** [comment]
There's an ongoing refactoring that impacts the code you've touched. It is best to re-evaluate this PR after those changes land.

**Comment by mimi89999** [comment]
@lvillani Do you have any ETA for when refactoring should be finished?

**Comment by mimi89999** [comment]
@lvillani @geek1011 I rebased on latest master. Could you please review this now?

**Comment by lvdvlr** [comment]
This is blocked by the `pkg-registry4` branch. This branch introduces changes that are sure to introduce conflicts when we merge/rebase that branch.

**Comment by lvillani** [comment]
This is blocked by the `pkg-registry4` branch. This branch introduces changes that will introduce conflicts once we merge/rebase that branch.

**Comment by mimi89999** [comment]
This breaks entries with `{{.version}}`. I need to fix that.

**Comment by mimi89999** [comment]
I updated this PR. Now it should work well.
@lvillani Do you you think that there might be a nicer way of implementing this?

**Comment by barpec12** [comment]
With the current version of Just-Install I cannot install Firefox on my computers, because it is installing version with english instead of my native language. I would appreciate merging this pull request to master branch.

**Comment by mimi89999** [comment]
@lvillani Now that you merged the registry4 changes, can I update this PR? Will you accept it?

**Comment by mimi89999** [comment]
@lvillani I updated this PR. Could you please review it?

**Review by lvillani — APPROVED** [review]

**Comment by mimi89999** [comment]
Thanks :smiley:

**Pull request merged**
